---
name: Pull Request
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: --no-color -q
          annotate: warning
